# Application name
spring.application.name=${SPRING_APPLICATION_NAME:user-service}
# Datasource configuration
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#spring.datasource.url=jdbc:mysql://localhost:3306/userdb
#spring.datasource.username=root
#spring.datasource.password=root
# Datasource configuration for AWS
spring.datasource.url=jdbc:mysql://userdb.cloog8yskvdh.eu-north-1.rds.amazonaws.com:3307/userdb
spring.datasource.username=root
spring.datasource.password=pet-project
# JPA configuration
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
# Server configuration
server.port=${SERVER_PORT:8080}
# Eureka server configuration
#eureka.client.service-url.defaultZone=${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka/}
eureka.instance.prefer-ip-address=true
eureka.instance.instance-id=${spring.application.name}:${random.uuid}
# Eureka server configuration for AWS
eureka.client.service-url.defaultZone=http://16.171.253.225:8761/eureka/